# Generated by Django 5.2.17 on 2026-08-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Cash / Ramburs"), ("stripe", "Card (Stripe)")],
                default="cash",
                max_length=20,
            ),
        ),
    ]
