# Generated by Django 5.2.17 on 2026-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(("valid_from__lt", models.F("valid_to"))),
                name="coupon_valid_from_before_valid_to",
            ),
        ),
    ]
