# Generated by Django 5.2.17 on 2026-09-11 14:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                default="default/user.jpg",
                upload_to=accounts.models.profile_image_upload_to,
                validators=[accounts.models.validate_profile_image_size],
            ),
        ),
    ]
