# Generated by Django 5.2.17 on 2026-08-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash")], default="cash", max_length=10
            ),
        ),
    ]
